config/routes.rb
Rails.application.routes.draw do
  resources :newsletters

  root 'home#show'

  resources :books
  resources :tvs
  resources :reviews
  resources :comments
  resources :articles
  resources :subscriptions
  devise_for :users

  get 'about/show'
  get 'about/terms'
  mount Ckeditor::Engine => '/ckeditor'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present? && user.admin?
      can :manage, :all
      can [:read, :create, :destroy], Ckeditor::Picture
      can [:read, :create, :destroy], Ckeditor::AttachmentFile
    elsif user.present? && !user.admin?
      can :read, :all
      can :create, Comment
      can :create, Review
      can :manage, Subscription
    else
      can :read, :all
    end
    can :access, :ckeditor
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :section, :user_id, :title, :content, presence: true

  scope :monday_mummies, -> { where(section: 'Monday Mummies') }
  scope :abuse_no_more, -> { where(section: 'Abuse No More') }
  scope :child_abuse, -> { where(section: 'Child Abuse') }
  scope :random, -> { where(section: 'Random') }
  scope :this_week, -> { where('created_at >= ?', 8.days.ago) }

  SECTIONS = ['Monday Mummies', 'Abuse No More', 'Child Abuse', 'Random']
end

app/models/book.rb
class Book < ActiveRecord::Base
  RATINGS = 1..5
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :article_id, :content, :user_id, presence: true
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user

  validates :rating, :content, presence: true
  validates_uniqueness_of :user_id, message: "You have already reviewed this book!"#, :scope => :friend_id
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user

  validates :sub_category, :user_id, :sub_fee, presence: true

  SUBSCRIPTION_CATEGORY = %w(Monthly Annual)
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  validates :youtube_url, :title, :description, :published, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  validate :image_size_validation

  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end

  def terms
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @newsletters = Newsletter.all
  end

  def show
  end

  def new
    @newsletter = Newsletter.new
  end

  def edit
  end

  def create
    @newsletter = Newsletter.new(newsletter_params)
    @newsletter.user = current_user

    respond_to do |format|
      if @newsletter.save
        NewsletterMailer.newsletter_created(@newsletter).deliver_now
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    def newsletter_params
      params.require(:newsletter).permit(:content, :user_id, :title)
    end
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :set_tv, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @tvs = Tv.all
  end

  def show
  end

  def new
    @tv = Tv.new
  end

  def edit
  end

  def create
    @tv = Tv.new(tv_params)

    respond_to do |format|
      if @tv.save
        format.html { redirect_to @tv, notice: 'Tv was successfully created.' }
        format.json { render :show, status: :created, location: @tv }
      else
        format.html { render :new }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tv.update(tv_params)
        format.html { redirect_to @tv, notice: 'Tv was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv }
      else
        format.html { render :edit }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tv.destroy
    respond_to do |format|
      format.html { redirect_to tvs_url, notice: 'Tv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tv
      @tv = Tv.find(params[:id])
    end

    def tv_params
      params.require(:tv).permit(:title, :description, :published, :youtube_url)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def parallax_pic(article)
    case
      when article.section == "Monday Mummies"
        image_tag "mummies.jpg", size: "1200x600"
      when article.section == "Abuse No More"
        image_tag "no_more.jpg", size: "1200x600"
      when article.section == "Child Abuse"
        image_tag "child_abuse.jpg", size: "1200x600"
      else
        image_tag "family.jpg", size: "1200x600"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disclaimer_helper.rb
module DisclaimerHelper

  def supported_browser?(user_agent_string)
    browser = Browser.new(ua: user_agent_string )
    !(browser.chrome? || (browser.ie? && browser.version.to_i < 9))
  end

  def already_shown

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tvs_helper.rb
module TvsHelper
end

app/views/newsletters/_form.html.haml
= form_for @newsletter do |f|
  - if @newsletter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@newsletter.errors.count, "error")} prohibited this newsletter from being saved:"
      %ul
        - @newsletter.errors.full_messages.each do |msg|
          %li= msg

  .input-field
    = f.label :title
    = f.text_field :title
  .input-field
    = f.cktext_area :content, class: 'ckeditor'
  .actions
    = button_tag type: "submit", class: "waves-effect waves-light btn" do
      %i.material-icons.right done_all
      Create Newsletter

app/views/newsletters/edit.html.haml
.container
  %h1 Editing newsletter

  = render 'form'
  %br/
  .row
    = link_to ('<i class="material-icons right">video_library</i> View Newsletter').html_safe, @newsletter, class: 'waves-effect waves-light pink darken-3 btn'

    = link_to ('<i class="material-icons left">call_received</i> Back').html_safe, newsletters_path, class: 'waves-effect waves-light pink darken-3 btn'

app/views/newsletters/index.html.haml
.container
  %h1 All Newsletters

  - @newsletters.each do |newsletter|
    .col.s12
      = link_to newsletter do
        .card-panel.grey.lighten-5.z-depth-1.hoverable
          .row.valign-wrapper
            %span.black-text
              %blockquote
                = newsletter.title
              %p.truncate.black-text
                = raw(newsletter.content)
              = link_to ('<i class="material-icons right">grade</i>').html_safe, '#!', class: 'secondary-content'
  %br

  - if can? :manage, :all
    .row
      = link_to ('<i class="material-icons">add</i> Create A Newsletter').html_safe, new_newsletter_path, 'data-tooltip' => 'Create A Newsletter',
      class: 'btn-floating btn-large tooltipped waves-effect waves-light pink darken-3', 'data-delay' => '50', 'data-position' => 'top'

app/views/newsletters/new.html.haml
.container
  %h1 New Newsletter

  = render 'form'
  %br/
  .row
    = link_to ('<i class="material-icons left">call_received</i> Back').html_safe, newsletters_path, class: 'waves-effect waves-light pink darken-3 btn'

app/views/newsletters/show.html.haml
%p#notice= notice

.section.grey.lighten-4
  .row.container
    %h2.header= @newsletter.title
    %p.grey-text.text-darken-3.lighten-3
      = raw(@newsletter.content)
    - if can? :manage, :all
      .row.container
        = link_to ('<i class="material-icons left">call_received</i> Back').html_safe, newsletters_path, class: 'waves-effect waves-light pink darken-3 btn'

        = link_to ('<i class="material-icons">edit</i> Edit Newsletter').html_safe, edit_newsletter_path(@newsletter), 'data-tooltip' => 'Edit Newsletter',
            class: 'btn-floating btn-large tooltipped waves-effect waves-light blue-grey darken-1', 'data-delay' => '50', 'data-position' => 'top'

        = link_to ('<i class="material-icons">delete</i> Delete Newsletter').html_safe, @newsletter, :method => :delete, :data => { :confirm => 'Are you sure?' } , 'data-tooltip' => 'Delete Newsletter',
            class: 'btn-floating btn-large tooltipped waves-effect waves-light red darken-1', 'data-delay' => '50', 'data-position' => 'top'