config/routes.rb
Rails.application.routes.draw do
  resources :newsletters

  root 'home#show'

  resources :books
  resources :tvs
  resources :reviews
  resources :comments
  resources :articles
  resources :subscriptions
  devise_for :users

  get 'about/show'
  get 'about/terms'
  mount Ckeditor::Engine => '/ckeditor'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present? && user.admin?
      can :manage, :all
      can [:read, :create, :destroy], Ckeditor::Picture
      can [:read, :create, :destroy], Ckeditor::AttachmentFile
    elsif user.present? && !user.admin?
      can :read, :all
      can :create, Comment
      can :create, Review
      can :manage, Subscription
    else
      can :read, :all
    end
    can :access, :ckeditor
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :section, :user_id, :title, :content, presence: true

  scope :monday_mummies, -> { where(section: 'Monday Mummies') }
  scope :abuse_no_more, -> { where(section: 'Abuse No More') }
  scope :child_abuse, -> { where(section: 'Child Abuse') }
  scope :random, -> { where(section: 'Random') }
  scope :this_week, -> { where('created_at >= ?', 8.days.ago) }

  SECTIONS = ['Monday Mummies', 'Abuse No More', 'Child Abuse', 'Random']
end

app/models/book.rb
class Book < ActiveRecord::Base
  RATINGS = 1..5
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :article_id, :content, :user_id, presence: true
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user

  validates :rating, :content, presence: true
  validates_uniqueness_of :user_id, message: "You have already reviewed this book!"#, :scope => :friend_id
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user

  validates :sub_category, :user_id, :sub_fee, presence: true

  SUBSCRIPTION_CATEGORY = %w(Monthly Annual)
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  validates :youtube_url, :title, :description, :published, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  validate :image_size_validation

  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end

  def terms
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @books = Book.all
    @reviews = Review.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :description, :image, :release_date, :author, :cost)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :set_tv, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @tvs = Tv.all
  end

  def show
  end

  def new
    @tv = Tv.new
  end

  def edit
  end

  def create
    @tv = Tv.new(tv_params)

    respond_to do |format|
      if @tv.save
        format.html { redirect_to @tv, notice: 'Tv was successfully created.' }
        format.json { render :show, status: :created, location: @tv }
      else
        format.html { render :new }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tv.update(tv_params)
        format.html { redirect_to @tv, notice: 'Tv was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv }
      else
        format.html { render :edit }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tv.destroy
    respond_to do |format|
      format.html { redirect_to tvs_url, notice: 'Tv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tv
      @tv = Tv.find(params[:id])
    end

    def tv_params
      params.require(:tv).permit(:title, :description, :published, :youtube_url)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def parallax_pic(article)
    case
      when article.section == "Monday Mummies"
        image_tag "mummies.jpg", size: "1200x600"
      when article.section == "Abuse No More"
        image_tag "no_more.jpg", size: "1200x600"
      when article.section == "Child Abuse"
        image_tag "child_abuse.jpg", size: "1200x600"
      else
        image_tag "family.jpg", size: "1200x600"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disclaimer_helper.rb
module DisclaimerHelper

  def supported_browser?(user_agent_string)
    browser = Browser.new(ua: user_agent_string )
    !(browser.chrome? || (browser.ie? && browser.version.to_i < 9))
  end

  def already_shown

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tvs_helper.rb
module TvsHelper
end

app/views/books/_book_club.html.haml
.row.center-align
  %h2 Watch this Space. Coming Soon!!!!

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :release_date
    = f.date_select :release_date
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :cost
    = f.number_field :cost
  .actions
    = f.submit 'Save'

app/views/books/_naked.html.haml
.row.center-align
  = image_tag('book_transparent.png', class: 'responsive-img')
.card.paint
  .card-content
    %span.card-title
      %h5.white-text NAKED
    %p.white-text NAKED is a memoir of three decades of my life and it focuses on my experiences​ with abuse, how it affected my mental health, how I developed emotional intelligence and how I now live an authentic life.

    %p.white-text It's a how to guide on how you too can rise from any situation and live your authentic life.

    %p.white-text I believe if everyone is empowered to live authentically, the generations after us will not have to struggle as much as some of us did. And we will be one step closer to world peace.
  .card-action
    %blockquote
      %h5.white-text Ese Walter

app/views/books/_review.html.haml
.row
  %h2.center-align Reviews for Naked

  - @reviews.each do |review|
    .col.s12
      .card-panel.blue-grey.lighten-5.z-depth-0.hoverable
        .row
          .col.s2
            %blockquote
              = image_tag("#{review.user.image}", class: 'circle responsive-img', size: '60x60')
              %p.truncate= review.user.name
          .col.s10
            %span.black-text
              = raw(review.content)
            %p
            - (1..review.rating).each do
              %i.material-icons grade


%br/
.row
  %ul.collapsible.popout{ 'data-collapsible' => 'accordion' }
    %li
      .collapsible-header.grey.lighten-4
        %i.material-icons perm_phone_msg
        Add Review
      .collapsible-body
        = render 'review_form'

app/views/books/_review_form.html.haml
.container
  = form_for Review.new do |f|
    .input-field
      = f.label :content
      = f.text_area :content, class: "materialize-textarea", id: 'textarea1'
    .input-field
      = f.label :rating
      %br/
      %br/
      = f.select :rating, options_for_select(Book::RATINGS)
    %br/
    .actions
      = button_tag type: "submit", class: "waves-effect waves-light btn" do
        %i.material-icons.right done_all
        Create Review
  %br/

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
.books
  .container
    .row
      .col.s12
        %ul.tabs.paint
          %li.tab.col.s3.active
            = link_to(('<i class="mdi-social-person"></i> Naked').html_safe, "#naked")
          %li.tab.col.s3
            = link_to(('<i class="mdi-social-person"></i> Reviews').html_safe, "#reviews")
          %li.tab.col.s3
            = link_to(('<i class="mdi-social-person"></i> Book Club').html_safe, "#club")

      #naked.col.s12
        = render 'naked'
      #reviews.col.s12
        = render 'review'
      #club.col.s12
        = render 'book_club'
    %br

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @book.name
%p
  %b Description:
  = @book.description
%p
  %b Image:
  = @book.image
%p
  %b Release date:
  = @book.release_date
%p
  %b Author:
  = @book.author
%p
  %b Cost:
  = @book.cost

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/tvs/_doaln.html.haml
%h1 Diary Of A Lagos Newbie

app/views/tvs/_form.html.haml
= form_for @tv do |f|
  - if @tv.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tv.errors.count, "error")} prohibited this tv from being saved:"
      %ul
        - @tv.errors.full_messages.each do |msg|
          %li= msg

  .input-field
    = f.label :title
    %span.material-icons.right mode_edit
    = f.text_field :title
  .input-field
    = f.label :description
    %span.material-icons.right mode_edit
    = f.text_area :description, class: "materialize-textarea", id: 'textarea1'
  .input-field
    = f.label :published
    = f.text_field :published, class: 'datepicker'
  .input-field
    = f.label :youtube_url
    %span.material-icons.right mode_edit
    = f.text_field :youtube_url
  .actions
    = button_tag type: "submit", class: "waves-effect waves-light btn" do
      %i.material-icons.right done_all
      Add Video

app/views/tvs/_fstv.html.haml
%h1 Femina Speaks TV
.row
  - @tvs.each do |tv|
    .col.s4
      .card.hoverable
        .card-image
          = link_to image_tag("http://img.youtube.com/vi/#{tv.youtube_url}/mqdefault.jpg", size: "350x250"), tv
          %span.card-title.truncate= tv.title
        .card-content
          %p.truncate= tv.description
        .card-action
          = link_to 'WATCH', tv
          - if can? :manage, :all
            = link_to ('<i class="material-icons">delete</i>  Delete Video').html_safe, tv, :method => :delete, :data => { :confirm => 'Are you sure?' }, 'data-tooltip' => 'Delete Video',
              class: 'btn-floating btn-large tooltipped waves-effect waves-light pink darken-3', 'data-delay' => '50', 'data-position' => 'top'
%br
- if can? :manage, :all
  = link_to ('<i class="material-icons">add</i> Add New Video').html_safe, new_tv_path, 'data-tooltip' => 'Add New Video',
    class: 'btn-floating btn-large tooltipped waves-effect waves-light pink darken-3', 'data-delay' => '50', 'data-position' => 'top'

app/views/tvs/_mtgt.html.haml
%h1 Making Tomorrow's Gentlemen Today

app/views/tvs/edit.html.haml
.container
  %h1 Edit Video

  = render 'form'
  %br/
  .row
    = link_to ('<i class="material-icons right">video_library</i> View Video').html_safe, @tv, class: 'waves-effect waves-light pink darken-3 btn'

    = link_to ('<i class="material-icons left">call_received</i> Back').html_safe, tvs_path, class: 'waves-effect waves-light pink darken-3 btn'

app/views/tvs/index.html.haml
.back
  .container
    .row
      .col.s12
        %ul.tabs.paint
          %li.tab.col.s6.active
            = link_to(('<i class="mdi-social-person"></i> MTGT').html_safe, "#mtgt")
          %li.tab.col.s6
            = link_to(('<i class="mdi-social-person"></i> DOALN').html_safe, "#doaln")

      #mtgt.col.s12
        = render 'mtgt'
      #doaln.col.s12
        = render 'doaln'
    %br

app/views/tvs/new.html.haml
.container
  %h1 Add New Video

  = render 'form'
  %br/
  .row
    = link_to ('<i class="material-icons left">call_received</i> Back').html_safe, tvs_path, class: 'waves-effect waves-light pink darken-3 btn'

app/views/tvs/show.html.haml
.back
  .container
    %p#notice= notice

    .row
      %h3.center-align= @tv.title

    .container
      .video-container
        %iframe.survey_segment{src: "//www.youtube.com/embed/#{@tv.youtube_url}", frameborder: "0", width: "853", height: "480"}

    .row
      %blockquote
        %h5= @tv.description
      %span Published :
      = @tv.published
    - if can? :manage, :all
      = link_to ('<i class="material-icons">edit</i> Edit Video').html_safe, edit_tv_path(@tv), 'data-tooltip' => 'Edit Video',
        class: 'btn-floating btn-large tooltipped waves-effect waves-light pink darken-3', 'data-delay' => '50', 'data-position' => 'top'

    = link_to ('<i class="material-icons left">call_received</i> Back').html_safe, tvs_path, class: 'waves-effect waves-light pink darken-3 btn'