config/routes.rb
Rails.application.routes.draw do
  resources :newsletters

  root 'home#show'

  resources :books
  resources :tvs
  resources :reviews
  resources :comments
  resources :articles
  resources :subscriptions
  devise_for :users

  get 'about/show'
  get 'about/terms'
  mount Ckeditor::Engine => '/ckeditor'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present? && user.admin?
      can :manage, :all
      can [:read, :create, :destroy], Ckeditor::Picture
      can [:read, :create, :destroy], Ckeditor::AttachmentFile
    elsif user.present? && !user.admin?
      can :read, :all
      can :create, Comment
      can :create, Review
      can :manage, Subscription
    else
      can :read, :all
    end
    can :access, :ckeditor
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :section, :user_id, :title, :content, presence: true

  scope :monday_mummies, -> { where(section: 'Monday Mummies') }
  scope :abuse_no_more, -> { where(section: 'Abuse No More') }
  scope :child_abuse, -> { where(section: 'Child Abuse') }
  scope :random, -> { where(section: 'Random') }
  scope :this_week, -> { where('created_at >= ?', 8.days.ago) }

  SECTIONS = ['Monday Mummies', 'Abuse No More', 'Child Abuse', 'Random']
end

app/models/book.rb
class Book < ActiveRecord::Base
  RATINGS = 1..5
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :article_id, :content, :user_id, presence: true
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user

  validates :rating, :content, presence: true
  validates_uniqueness_of :user_id, message: "You have already reviewed this book!"#, :scope => :friend_id
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user

  validates :sub_category, :user_id, :sub_fee, presence: true

  SUBSCRIPTION_CATEGORY = %w(Monthly Annual)
end

app/models/tv.rb
class Tv < ActiveRecord::Base
  validates :youtube_url, :title, :description, :published, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  validate :image_size_validation

  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :set_tv, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @tvs = Tv.all
  end

  def show
  end

  def new
    @tv = Tv.new
  end

  def edit
  end

  def create
    @tv = Tv.new(tv_params)

    respond_to do |format|
      if @tv.save
        format.html { redirect_to @tv, notice: 'Tv was successfully created.' }
        format.json { render :show, status: :created, location: @tv }
      else
        format.html { render :new }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tv.update(tv_params)
        format.html { redirect_to @tv, notice: 'Tv was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv }
      else
        format.html { render :edit }
        format.json { render json: @tv.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tv.destroy
    respond_to do |format|
      format.html { redirect_to tvs_url, notice: 'Tv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tv
      @tv = Tv.find(params[:id])
    end

    def tv_params
      params.require(:tv).permit(:title, :description, :published, :youtube_url)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def parallax_pic(article)
    case
      when article.section == "Monday Mummies"
        image_tag "mummies.jpg", size: "1200x600"
      when article.section == "Abuse No More"
        image_tag "no_more.jpg", size: "1200x600"
      when article.section == "Child Abuse"
        image_tag "child_abuse.jpg", size: "1200x600"
      else
        image_tag "family.jpg", size: "1200x600"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disclaimer_helper.rb
module DisclaimerHelper

  def supported_browser?(user_agent_string)
    browser = Browser.new(ua: user_agent_string )
    !(browser.chrome? || (browser.ie? && browser.version.to_i < 9))
  end

  def already_shown

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tvs_helper.rb
module TvsHelper
end

app/views/layouts/_disclaimer.html.haml
#disclaimer.modal
  .modal-content
    %h5.center-align Disclaimer!
    %p.blue-text.text-darken-4 All information available on Femina Speaks Media are for information purposes only and should not replace professional advice and/or medication.
  .modal-footer
    = link_to 'Ok' , '#!' , class: 'modal-action modal-close waves-effect waves-green btn-flat'

app/views/layouts/_google_tag_manager.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-M9Z57K"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M9Z57K');</script>
<!-- End Google Tag Manager -->

app/views/layouts/_side_bar.html.haml
%ul#slide-out.side-nav.paint.lighten-4
  %li
    %h3= link_to 'Watch', tvs_path, class: 'waves-effect waves-light white-text text-darken-4'
  %li
    %h3= link_to 'Listen', "#", class: 'waves-effect waves-light white-text text-darken-4'
  %li
    %h3= link_to 'Read', articles_path, class: 'waves-effect waves-light white-text text-darken-4'
  %li= link_to 'Book', books_path, class: 'waves-effect waves-light white-text text-darken-4'
  -#%li= link_to 'Support Group', subscriptions_path
  %li
    %h3= link_to 'About', about_show_path, class: 'waves-effect waves-light white-text text-darken-4'
  - if user_signed_in?
    - if current_user.image.present?
      %li
        %h3= image_tag(current_user.image, class: 'circle responsive-img', size: '58x40')
    - else
      %li
        %h3= image_tag('default_avatar.png', class: 'circle responsive-img', size: '58x40')
    %li.white-text #{current_user.name}
    - if can? :manage, :all
      %li.white-text= link_to 'Newsletters', newsletters_path, class: 'waves-effect waves-light white-text text-darken-4'
    %li.white-text= link_to 'Edit profile', edit_user_registration_path, class: 'waves-effect waves-light white-text text-darken-4'
    %li.white-text= link_to "Logout", destroy_user_session_path, method: :delete, class: 'waves-effect waves-light white-text text-darken-4'
  - else
    %li
      %h3= link_to "Join", new_user_session_path, class: 'navbar-link waves-effect waves-light white-text text-darken-4'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ese Walter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.png'
    %link{href: 'https://fonts.googleapis.com/icon?family=Material+Icons', rel: 'stylesheet'}
    = csrf_meta_tags
  %body
    %ul#dropdown1.dropdown-content.paint
      - if can? :manage, :all
        %li= link_to 'Newsletters', newsletters_path
      %li= link_to 'Edit profile', edit_user_registration_path
      %li.divider
      %li= link_to "Logout", destroy_user_session_path, method: :delete
    .navbar-fixed
      %nav
        .nav-wrapper.wrap-nav
          .container
            -#= link_to(image_tag('femina.png', size: '200x200', class: 'responsive-img'), root_path, class: "brand-logo")
            = image_tag('logo.png', size: '90x90', class: 'responsive-img')
            = link_to 'Femina Speaks', root_path, class: "brand-logo"
            %ul#nav-mobile.right.hide-on-med-and-down
              %li= link_to 'About', about_show_path
              %li= link_to 'Watch', tvs_path
              %li= link_to 'Listen', "#"
              %li= link_to 'Read', articles_path
              %li= link_to 'Book', books_path
              -#%li= link_to 'Support Group', subscriptions_path
              - if user_signed_in?
                - if current_user.image.present?
                  %li= image_tag(current_user.image, class: 'circle responsive-img', size: '58x40')
                - else
                  %li= image_tag('default_avatar.png', class: 'circle responsive-img', size: '58x40')
                %li= link_to ("<i class='material-icons right'>arrow_drop_down</i> #{current_user.name}").html_safe, '#', class: 'dropdown-button', 'data-activates' => 'dropdown1'
              - else
                %li= link_to "Join", new_user_session_path, class: 'navbar-link'
            = link_to ("<i class='mdi-navigation-menu'></i>").html_safe, "#", class: 'button-collapse', 'data-activates'=>"slide-out"

    = render 'layouts/side_bar'
    = render 'layouts/google_tag_manager'
    = render 'layouts/disclaimer'
    = yield
    .col.s12.footer1.page-footer.center-align
      .container
        .row.pad
          .col.s4
            %li= link_to ('<i class="material-icons left">playlist_add</i> Live').html_safe, '#', class: 'waves-effect waves-light paint2 btn-large'
          .col.s4
            %li= link_to ('<i class="material-icons left">assignment</i> Love').html_safe, '#', class: 'waves-effect waves-light paint2 btn-large'
          .col.s4
            %li= link_to ('<i class="material-icons right">send</i> Laugh').html_safe, '#', class: 'waves-effect waves-light paint2 btn-large'
      .footer-copyright
        .container
          = link_to image_tag("facebook.png", size: '100x100'), 'https://www.facebook.com/esefemina'
          = link_to image_tag("google_buzz.png", size: '100x100'), 'https://plus.google.com/+EseWalter/posts'
          = link_to image_tag("twitter.png", size: '100x100'), 'https://twitter.com/kendrickzma'
        .lower-footer
          %h6.white-text.text-darken-4 Copyright © 2015 Femina Speaks Media, All rights reserved.
          %p.white-text.text-darken-4 No part of this website may be reproduced or transmitted in any form, by any means.  It is illegal to use without express permission.
          %p.white-text A violation of this will attract a N1,000,000 (one million naira) fine and possible law suit.
          %p.white-text Please read the full Copyright terms under #{ link_to 'TERMS OF USE.', about_terms_path }